package com.viewfunction.docg.coreRealm.realmServiceCore.term;

public enum AttributeDataType {
    BOOLEAN,INT,SHORT,LONG,FLOAT,DOUBLE,TIMESTAMP,DATE,DATETIME,TIME,STRING,BYTE,DECIMAL,
    BOOLEAN_ARRAY,INT_ARRAY,SHORT_ARRAY,LONG_ARRAY,FLOAT_ARRAY,DOUBLE_ARRAY,TIMESTAMP_ARRAY,DATE_ARRAY,DATETIME_ARRAY,TIME_ARRAY,STRING_ARRAY,BYTE_ARRAY,DECIMAL_ARRAY,
    BINARY
}
