package com.viewfunction.docg.coreRealm.realmServiceCore.term;

public enum AttributeDataType {
    BOOLEAN,INT,SHORT,LONG,FLOAT,DOUBLE,DATE,STRING,BINARY,BYTE,DECIMAL,BOOLEAN_ARRAY,INT_ARRAY,SHORT_ARRAY,
    LONG_ARRAY,FLOAT_ARRAY,DOUBLE_ARRAY,DATE_ARRAY,STRING_ARRAY,BINARY_ARRAY,DECIMAL_ARRAY
}
