package relationExtractionRules;
import com.viewfunction.docg.knowledgeManage.applicationCapacity.relationExtraction.ruleEngineFactsGenerators.RelationExtractionRulesGenerator.Message

rule "Hello World"
  when
    m : Message( status == Message.HELLO, message : message )
  then
    System.out.println( message );
    modify ( m ) { message = "Goodbye cruel world",
                   status = Message.GOODBYE };
end

rule "Good Bye"
  when
    Message( status == Message.GOODBYE, message : message )
  then
    System.out.println( message );
end